import type {
  CurrencyCode,
  PaymentMethodType,
} from '@payments/domain/subdomains/payment/contracts/payment-intent.types';

/**
 * Generic request to create a payment.
 *
 * Contains fields common to all providers.
 * Each provider uses the fields it needs and ignores the rest.
 *
 * Validation of which fields are required for each
 * provider+method combination happens in the specific Builder.
 */
export interface CreatePaymentRequest {
  orderId: string;
  amount: number;
  currency: CurrencyCode;
  method: {
    type: PaymentMethodType;
    token?: string;
  };

  returnUrl?: string;
  cancelUrl?: string;
  customerEmail?: string;

  /** Idempotency key for safe retries. Generated by IdempotencyKeyFactory. */
  idempotencyKey?: string;

  metadata?: Record<string, unknown>;
}

export interface ConfirmPaymentRequest {
  intentId: string;
  returnUrl?: string;
  /** Idempotency key for safe retries. Generated by IdempotencyKeyFactory. */
  idempotencyKey?: string;
}

export interface CancelPaymentRequest {
  intentId: string;
  /** Idempotency key for safe retries. Generated by IdempotencyKeyFactory. */
  idempotencyKey?: string;
}

export interface GetPaymentStatusRequest {
  intentId: string;
  /** Idempotency key for safe retries. Generated by IdempotencyKeyFactory. */
  idempotencyKey?: string;
}
